### ISSUE TITLE
contact form

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#1]
assigned @JorisLambrechts 

Zet boven veld "your message" nog een toggle select met de zin "Do you want to receive an account for the IDEM database?"
Plaats de zin en toggle select voor de nieuwsbrief hiereronder, dan staan ze samen. 

Denk best om SPAM te voorkomen dat we een captcha toevoegen, niet?
Engelse versie, niet toe moeilijk.

**Comment by JorisLambrechts** [comment]
captcha komt als de site live is, want de domeinnaam gaat nog veranderen

**Comment by JorisLambrechts** [comment]
zie #14
