### ISSUE TITLE
simple contact page

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#11]
assigned @JorisLambrechts 

Is er geen simple contact page plug-in voor /alamire/contact ?

Nog een lijn toevoegen aan contactpage. Kan je ook de zinnetjes onderaan aanpassen zoals op het design. 

I request an account for the IDEM database
I would like to be added to the Alamire Foundation contact list

![capture](https://cloud.githubusercontent.com/assets/3798589/8519233/7eee1bbe-23d1-11e5-8f20-8ecdb7decdf8.JPG)

**Comment by JorisLambrechts** [comment]
in de opties van de simple contact plugin kan je de text aanpassen die boven het formulier staat
