### ISSUE TITLE
link achter Images

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#13]
assigned @JorisLambrechts 

Ik heb een nieuw metadataveld aangemaakt voor manuscripten genaamd 'Images'
Hierin staat de link naar het volledige manuscript in de Mirador viewer. Wanneer een bezoeker op 'Images' klikt, moet de link opengaan in een nieuwe tabblad. 

Zie test item id/9

![capture](https://cloud.githubusercontent.com/assets/3798589/8520192/91bd6a0e-23d8-11e5-87c1-29dca4cf7b2d.JPG)

**Comment by roxannewyns** [comment]
die 1 en 2 moet dus niet. Images is eingelijk gewoon de link naar het complex object in Mirador viewer
![capture](https://cloud.githubusercontent.com/assets/3798589/8520771/c1fd536e-23dd-11e5-8311-d705a3f78790.JPG)

**Comment by JorisLambrechts** [comment]
Weet je al wat voor id's we gaan hebben voor die afbeeldingen en of die als metadata mee komen? Dus of het een IE (vb. IE2710861) of FL (vb. FL2710911)  id is of nog iets anders.

**Comment by roxannewyns** [comment]
als ik op images klik blijf ik nog op dezelfde pagina
