### ISSUE TITLE
schijffout in reply can simple contact form

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#27]
assigned @JorisLambrechts 

Een detail, maar in de mail die de administrator krijgt staat een schrijffout. Het moet 'wiches' zijn ipv 'whiches'

Whishes to receive an IDEM database account: Yes

Whishes to receive the newsletter: Yes

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Alamire/commit/bfe5f00d34647e84bbdfb01fa736322b4a6a15e2
