### ISSUE TITLE
search result/browse pagina aanmaken

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#3]
assigned @JorisLambrechts 

Zie ook mijn mail. 

Te publiceren metadata + afbeelding

Manuscript label
Holding institution
Shelfmark
Content

**Comment by JorisLambrechts** [comment]
moeten nieuwsberichten ook op de solr/browse-pagina verschijnen of enkel de manuscripten?

**Comment by roxannewyns** [comment]
Enkel manuscripten.
