### ISSUE TITLE
link achter afbeelding steken naar de viewer

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#32]
Link naar de viewer  toegoeven aan de afbeeldingen zodat de gebruiker erop kan klikken en rechtstreeks naar de viewer gaat. 

Link naar viewer zit in het item type metadata element 'Viewer link'.
Viewer openen in een nieuw tabblad. 

Indien er meerdere thumbnails staan, mag je gewoon dezelfde link erachter steken. 

![alamire](https://cloud.githubusercontent.com/assets/3798589/14601522/c11b502e-0562-11e6-9778-2d49729e95f5.JPG)

**Comment by roxannewyns** [comment]
Door de wijzigingen plakken de beelden weer tegen elkaar. Er moet een witruimte tussenzitten. 

![capture](https://cloud.githubusercontent.com/assets/3798589/15210394/a8a45b8a-1836-11e6-9b03-1425e41ddc07.JPG)

**Comment by JorisLambrechts** [comment]
was normaal opgelost in https://github.com/libis/Alamire/commit/4730a6eb8c4dd4ca6cb796ba49db17beb503836f dus na een hard refresh zou het wel ok moeten zijn

**Comment by roxannewyns** [comment]
ja, het is in orde nu
