### ISSUE TITLE
New aanpassen in 'In the spotlight'

### ISSUE THREAD

**Issue by roxannewyns** [libis/Alamire#4]
assigened @JorisLambrechts 

Waarschijnlijk gaat Alamire niet veel nieuwsberichten hebben. Ze gaan hier dus ook nieuw toegevoegde mansucripten in de kijker willen zetten. Beter dus algemene titel zoals In the spotlight of Highlights.

**Comment by JorisLambrechts** [comment]
Welke velden moeten er dan getoond worden in deze kolom.?. Nu staat er het label en 'content'.

**Comment by roxannewyns** [comment]
Neem voorlopig title, content en description. 
Het gaan meestal manuscripten zijn maar niet altijd, dus beter ook andere metadata velden. 
In title komt sowieso ook het manuscript label te staan.
